[package]
name = "bevy-example"
version = "1.0.5"
authors = ["Robert Bisewski <rbisewski@ibiscybernetics.com>"]
edition = "2021"
rust-version = "1.62.1"
resolver = "2"

[profile.release]
opt-level = 1
debug = false
debug-assertions = false
overflow-checks = false
lto = false
panic = 'unwind'
incremental = true
codegen-units = 16
rpath = false
strip = "symbols"

[dependencies]
bevy = "0.8.0"
json = "0.12.4"
rand = "0.8.5"
