[package]
name = "bevy-example"
version = "1.0.1"
authors = ["Robert Bisewski <contact@ibiscybernetics.com>"]
edition = "2021"
rust-version = "1.57"
resolver = "2"

[profile.release]
lto = "thin"
codegen-units = 4

[dependencies]
bevy = "0.5.0"
rand = "0.8.4"
