[package]
name = "bevy-example"
version = "1.0.3"
authors = ["Robert Bisewski <contact@ibiscybernetics.com>"]
edition = "2021"
rust-version = "1.59"
resolver = "2"

[profile.release]
opt-level = 0
debug = false
debug-assertions = false
overflow-checks = false
lto = false
panic = 'unwind'
incremental = true
codegen-units = 16
rpath = false
strip = "symbols"

[dependencies]
bevy = "0.6.1"
rand = "0.8.5"
